### ISSUE TITLE
安装完后显示TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by LoveGT** [wanglin2/simple-flow-chart#1]
vue: 2.7
node: 14
yarn: v1.22.19
TypeError: this.getOptions is not a function

我安装了该插件后 显示提示less less-loader按装 安装候提示TypeError: this.getOptions is not a function

**Comment by wanglin2** [comment]
安装的版本太高了，less降到4或3的版本试试

**Comment by LoveGT** [comment]
谢谢 我改成less: 3 less-loader:6.0.0就行了

**Comment by prometheus-alien** [comment]
`npm i less@3.0.4 -D`
`npm i less-loader@5.0.0 -D`


如果需要安装less及less-loader，按以上安装即可。
